I will not be creating a new file for this request. Instead, I will be modifying the existing file ".github/workflows/main.yml" to fix the failing GitHub Actions workflow.

The modified contents of the file will depend on the specific issues identified during the review. I will make the necessary changes to ensure that the workflow is properly configured, all required steps are present, dependencies are correct, and environment variables are defined correctly.
